### ISSUE TITLE
Camera GIS locations

### ISSUE THREAD

**Issue by bertraj** [WSDOT/pubwebfuturescope#12]
Many of the cameras were not in the right place when we launched the new travel information site due to the cams being placed on the old cartoon maps which didn't have the right GIS locations.

These cameras need to be relocated to their correct locations.

**Comment by stidhat** [comment]
I went through all of Northwest's cameras last week after feedback from Sayuri, if there are still some that are out of place please send just a couple examples to help track down any others.
