### ISSUE TITLE
Remove accordions for weather detail

### ISSUE THREAD

**Issue by nellkinsell** [WSDOT/pubwebfuturescope#26]
**User story:**
As a traveler I want to get weather information at a glance and not miss it so that I can plan my travel and get going.

**Requirements:**

- Provide alternative design to collapsing extended weather information in an accordian
- Make sure that the design is usable and efficient for travelers 

**Requested by:**
Jeremy Bertrand

**Requested date:**
2/10/2022

**Needed by:**
Q1/2/3/4 YYYY

**Priority:**
High/Medium/Low

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by jhudsonWA** [comment]
@nellkinsell A solution to remove the accordions was shipped into production today 6/7/2022.
