### ISSUE TITLE
Improve search results for traffic cameras

### ISSUE THREAD

**Issue by nellkinsell** [WSDOT/pubwebfuturescope#32]
**User story:**
As a traveler/rule seeker/watchdog/business partner I want to get search results and links for traffic cameras so that I quickly plan my travel.

**Requirements:**
- Review search terms
- Implement metadata on travel map and list 

**Requested by:**
Jeremy Bertrand

**Requested date:**
2/6/22

**Needed by:**
Q2 2022

**Priority:**
Medium

**Additional context**
Add any other context or screenshots about the feature request here

**Comment by nellkinsell** [comment]
@bertraj - Are you ready to hand off the key terms that you and Alexis finalized? I think this could move over to the dev teams, if you are ready.

**Comment by bertraj** [comment]
[Meta Data Changes for Search.docx](https://github.com/WSDOT/pubwebfuturescope/files/8654030/Meta.Data.Changes.for.Search.docx)

Here are the changes we need to help search be more successful.
