### ISSUE TITLE
Fix links in GovDelivery emails to go directly to alerts

### ISSUE THREAD

**Issue by bertraj** [WSDOT/pubwebfuturescope#45]
**User story:**
As a traveler I want to click on a link in the email sent to me so that I can see the location of the alert on a map. 

**Requirements:**
Link directly to the alert rather than just linking to a general map. 

**Requested by:**
Jeremy Bertrand

**Requested date:**
MM/DD/YYYY

**Needed by:**
Q 3 2022

**Priority:**
Medium

**Additional context**

**Comment by stidhat** [comment]
This is working now.
