### ISSUE TITLE
Project search - weight improvements

### ISSUE THREAD

**Issue by carlsob** [WSDOT/pubwebfuturescope#52]
**User story:**
As a traveler/watchdog, when I search at https://wsdot.wa.gov/construction-planning/search-projects, I want to see projects that are still in construction/pre-construction before completed projects. 

Right now, I believe the search shows projects in a random order when you set a filter or enter a keyword. 

**Requirements:**
Investigation into development.

**Requested by:**
Christina Werner

**Requested date:**
Feb 2022

**Additional context**
This request comes from Tina by way of phone calls from the public experiencing confusion w/ the project search.

**Comment by waynedyck** [comment]
**Construction** and **Pre-construction** check boxes are now enabled on the default view.

**Comment by waynedyck** [comment]
We can't weight the "completed" status tag. For now we are going to return to what we did on the old which is to append the text "Complete MONTH YEAR" to the title.
