### ISSUE TITLE
Create Tiger Mt pass page

### ISSUE THREAD

**Issue by nellkinsell** [WSDOT/pubwebfuturescope#60]
**User story:**
As a traveler I want to be able to search and find snow and weather information about tiger mt so that I can plan a trip.

**Requirements:**
Create and publish a mountain pass page for tiger mt.

**Requested by:**
Northwest region

**Requested date:**
MM/DD/YYYY

**Needed by:**
Q4 2022

**Priority:**
- Medium Demand
- Medium Impact
- Extra-small Effort

**Additional context**
Follow template at https://wsdotwebhelp.gitbook.io/web-style-guide/page-types/mountain-passes

**Comment by bertraj** [comment]
This has been created, waiting on NW to give the ok.

**Comment by bertraj** [comment]
Page created and is live
